---
- name: Reiniciar servidor Windows
  hosts: windows_servers  # Grupo de hosts definido en el inventario
  gather_facts: no  # No recolectar facts, ya que solo estamos reiniciando

  tasks:
    - name: Reiniciar el servidor Windows
      ansible.windows.win_reboot:
        reboot_timeout: 600  # Tiempo de espera para que el servidor se reinicie (en segundos)
